apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-ms
    labels:
        app: web-ms
spec:
    # modify replicas according to your case
    replicas: 2
    selector:
        matchLabels:
            app: web-ms
    template:
        metadata:
            labels:
                app: web-ms
        spec:
            containers:
                - name: web-ms
                  image: gcr.io/atomic-sled-388523/web-app:latest
                  ports:
                      - containerPort: 4000
                  env:
                      - name: PORT
                        value: "4000"
                      - name: MONGO_URI
                        value: "mongodb+srv://DaGoblin:LearningDBAccess@cluster0.vy8qrqg.mongodb.net/?retryWrites=true&w=majority"
                      - name: JWTSECRET
                        valueFrom:
                            secretKeyRef:
                                key: password
                                name: jwt-secret
                      - name: AUTH_SERVICE
                        value: "auth-ms:4000"
                      - name: DATA_SERVICE
                        value: "data-ms:4000"
